### ISSUE TITLE
Error:Bad service configuration file, or exception thrown while constructing Processor object

### ISSUE THREAD

**Issue by jxarenas19** [smaugho/declex#207]
Buenas tardes,cuando intento crear un proyecto desde cero he incluyo las versión mas reciente declex-api-2.0.a.16,muestra el siguiente error cuando corro el proyecto

Error:Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.dspot.declex.DeclexProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/helger/jcodemodel/AbstractJType

**Comment by smaugho** [comment]
Hola, el error realmente no me queda claro a qué pueda estar debido, pudiera por favor compartir el proyecto para revizarlo acá?, si no le es posible, sería bueno si puede compatir su archivo gradle, y confirmar si el error le ocurre incluso sin usar aún anotaciones de DecleX. 

Confirmar también por favor, si usando las versiones anteriores también le ocurre, o si es sólamente con la última versión. 

Por favor si puediera crear futuros issue en Inglés sería ideal para que la comunidad pueda revizarlos sin limitaciones de Idioma.  

Muchísimas gracias de antemano

**Comment by jxarenas19** [comment]
Good evening, I started using the framework in version 1.2.8-SNAPSHOT and everything worked correctly, but the colleague who recommended it told me that in the later versions there were several improvements and changes, then I decided to update and create a project from the beginning and add version 2.a.0.16 and the problem starts, if I remove the framework the project works perfectly and if I put the old version too, the problem arises when I update it. I do not share the project because it is a new project created in the android studio, I have another study project created with the framework that I have with the old version and it works perfectly this very good, but I want to take advantage of the new improvements of the new versions, muchas gracias por la atención

**Comment by smaugho** [comment]
Could you please tell what version of Android Studio are you using?

I will check in Android Studio 3.0 like this:

I will create a new project, 

I simply will add DecleX libs like:

```groovy
    annotationProcessor 'com.dspot:declex:2.0.a.16'
    compile 'com.dspot:declex-api:2.0.a.16'
    compile 'com.dspot:declex-actions:2.0.a.8'
```

I will let you know the test result.

**Comment by jxarenas19** [comment]
Good morning, problem solved, it seems that the issue was in the download of the dependencies because I had put the * .jar direct.Thanks!

**Comment by smaugho** [comment]
Got it, thanks!!... Enjoy version 2 (note, it is still in beta development)!!
